### ISSUE TITLE
Cannot get nativeLoad method

### ISSUE THREAD

**Issue by yoesdinar** [afiqiqmal/SharedChamber#6]
I found this error when the app  initialize.
```
Cannot get nativeLoad method
    java.lang.NoSuchMethodException: nativeLoad [class java.lang.String, class java.lang.ClassLoader, class java.lang.String]
    at java.lang.Class.getMethod(Class.java:2068)
        at java.lang.Class.getDeclaredMethod(Class.java:2047)
        at com.facebook.soloader.SoLoader.getNativeLoadRuntimeMethod(SoLoader.java:297)
        at com.facebook.soloader.SoLoader.initSoLoader(SoLoader.java:249)
        at com.facebook.soloader.SoLoader.initImpl(SoLoader.java:156)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:131)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:115)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:142)
        at com.chamber.java.library.SharedChamber.initChamber(SharedChamber.java:86)
```

it might be similar to this?  https://github.com/facebook/fresco/issues/2115

**Comment by xaluxs** [comment]
The same happens Android API :28,  Moto e(6) plus

```
2020-11-13 12:01:15.705 18548-18548/com.spooky.app W/SoLoader: Cannot get nativeLoad method
    java.lang.NoSuchMethodException: nativeLoad [class java.lang.String, class java.lang.ClassLoader, class java.lang.String]
        at java.lang.Class.getMethod(Class.java:2068)
        at java.lang.Class.getDeclaredMethod(Class.java:2047)
        at com.facebook.soloader.SoLoader.getNativeLoadRuntimeMethod(SoLoader.java:297)
        at com.facebook.soloader.SoLoader.initSoLoader(SoLoader.java:249)
        at com.facebook.soloader.SoLoader.initImpl(SoLoader.java:156)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:131)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:115)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:142)
        at com.chamber.kotlin.library.SharedChamber$Companion.initChamber(SharedChamber.kt:1262)
        at com.spooky.app.App.onCreate(App.kt:44)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5960)
        at android.app.ActivityThread.access$1200(ActivityThread.java:216)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1712)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:235)
        at android.app.ActivityThread.main(ActivityThread.java:6760)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
```

**Comment by hamdyby** [comment]
J'ai le même problème ou presque
Vous avais une solutions ?
Merci d'avance

StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/content/Context;->bindServiceAsUser(Landroid/content/Intent;Landroid/content/ServiceConnection;ILandroid/os/Handler;Landroid/os/UserHandle;)Z
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getMethod(Class.java:2064)
	at java.lang.Class.getDeclaredMethod(Class.java:2047)
	at aLZ.a(PG:11)
	at aMw.a(PG:11)
	at aMa.a(PG:43)
	at cBg.<init>(PG:4)
	at cAx.run(PG:9)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by muhammadatifarif** [comment]
W/SoLoader: Cannot get nativeLoad method
    java.lang.NoSuchMethodException: java.lang.Runtime.nativeLoad [class java.lang.String, class java.lang.ClassLoader, class java.lang.String]
        at java.lang.Class.getMethod(Class.java:2072)
        at java.lang.Class.getDeclaredMethod(Class.java:2050)
        at com.facebook.soloader.SoLoader.getNativeLoadRuntimeMethod(SoLoader.java:297)
        at com.facebook.soloader.SoLoader.initSoLoader(SoLoader.java:249)
        at com.facebook.soloader.SoLoader.initImpl(SoLoader.java:156)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:131)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:115)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:142)
        at com.ibm.jazzcash.repository.local.SecureSharedPref.<clinit>(SecureSharedPref.kt:56)
        at com.ibm.jazzcash.util.Constants.<clinit>(Constants.kt:218)
        at com.ibm.jazzcash.config.ConfigResolver.getClientId(ConfigResolver.kt:21)
        at com.ibm.jazzcash.Constant.<clinit>(Constant.kt:10)
        at com.ibm.jazzcash.model.retrofit.Service.getService(Service.kt:62)
        at com.ibm.jazzcash.di.ModuleKt$networkModule$1$1.invoke(Module.kt:486)
        at com.ibm.jazzcash.di.ModuleKt$networkModule$1$1.invoke(Module.kt:486)
        at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:54)
        at org.koin.core.instance.SingleDefinitionInstance.get(SingleDefinitionInstance.kt:40)
        at org.koin.core.definition.BeanDefinition.resolveInstance(BeanDefinition.kt:70)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:165)
        at org.koin.core.scope.Scope.get(Scope.kt:128)
        at com.ibm.jazzcash.di.ModuleKt$remoteRepoModule$1$1.invoke(Module.kt:678)
        at com.ibm.jazzcash.di.ModuleKt$remoteRepoModule$1$1.invoke(Module.kt:468)
        at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:54)
        at org.koin.core.instance.SingleDefinitionInstance.get(SingleDefinitionInstance.kt:40)
        at org.koin.core.definition.BeanDefinition.resolveInstance(BeanDefinition.kt:70)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:165)
        at org.koin.core.scope.Scope.get(Scope.kt:128)
        at com.ibm.jazzcash.di.ModuleKt$loginModule$1$2.invoke(Module.kt:678)
        at com.ibm.jazzcash.di.ModuleKt$loginModule$1$2.invoke(Module.kt:284)
        at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:54)
        at org.koin.core.instance.SingleDefinitionInstance.get(SingleDefinitionInstance.kt:40)
        at org.koin.core.definition.BeanDefinition.resolveInstance(BeanDefinition.kt:70)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:165)
        at org.koin.core.scope.Scope.get(Scope.kt:128)
        at com.ibm.jazzcash.di.ModuleKt$loginModule$1$1.invoke(Module.kt:678)
        at com.ibm.jazzcash.di.ModuleKt$loginModule$1$1.invoke(Module.kt:283)
        at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:54)
        at org.koin.core.instance.FactoryDefinitionInstance.get(FactoryDefinitionInstance.kt:37)
        at org.koin.core.definition.BeanDefinition.resolveInstance(BeanDefinition.kt:70)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:165)
        at org.koin.core.scope.Scope.get(Scope.kt:128)
        at com.ibm.jazzcash.base.BaseActivity$special$$inlined$inject$default$3.invoke(ComponentCallbackExt.kt:51)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.ibm.jazzcash.base.BaseActivity.getLoginViewModel(BaseActivity.kt:991)
        at com.ibm.jazzcash.base.BaseActivity.onCreate(BaseActivity.kt:131)
        at com.ibm.jazzcash.view.splash.SplashActivity.onCreate(SplashActivity.kt:56)
        at android.app.Activity.performCreate(Activity.java:8207)
        at android.app.Activity.performCreate(Activity.java:8191)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3819)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4022)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
W/SoLoader:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
        
        
        getting same issue please do let me know if we have any fix.
?
